### ISSUE TITLE
Cuckoo: equals and serialization as frame type 7

### ISSUE THREAD

**Issue by akshay-xp** [akshay-xp/distillate#220]
## Context
Spec: `.claude/specs/2026-09-22-cuckoo.md` (local, gitignored)

## What to build
Type 7 frame: params block (`n`, `epsilon`, seed, `f`, bucket count, count) padded to 8, then the packed slot words padded to 8. Geometry stored, not re-derived. `toBytes`/`fromBytes`, `toJSON`/`fromJSON`, `equals`.

## Acceptance Criteria
- [ ] `toBytes`/`fromBytes` round-trip byte-identically, including after evictions and deletes; `toJSON`/`fromJSON` use the shared envelope
- [ ] `equals` is byte equality of `toBytes`
- [ ] `fromBytes` rejects a wrong type, unknown hash variant, bad lengths, nonzero padding, `f` out of range, and a count that disagrees with the occupied slots, each with a typed `SerializationError`
- [ ] The serialization fuzz suite covers cuckoo and never sees an untyped error
- [ ] The slot words start 8-byte aligned in the frame, asserted by test
- [ ] Building the same keys in the same order with the same seed gives byte-identical frames

## Blocked by
#219

**Comment by akshay-xp** [comment]
## Implementation Plan

> Run `/tdd 220` to execute. Worktree: `.claude/worktrees/cuckoo`.

**Goal:** `equals`, `toBytes`/`fromBytes` and `toJSON`/`fromJSON` for `CuckooFilter` as DSTL frame type 7, rejecting every malformed frame with a typed error.

**Spec:** `.claude/specs/2026-09-22-cuckoo.md` *(local, gitignored)*

**Frame layout pinned by this plan** (#221 documents it and the Go reader reads it). Hash variant 0; body offsets are little-endian:

```
n u32 @0 | seed u32 @4 | epsilon f64 @8 | f u32 @16 | buckets u32 @20 | count u32 @24 | pad 4 @28
slot words: ceil(4*f*buckets / 32) u32 words @32, padded to a multiple of 8
```

- The params block is 32 bytes, so the words start at frame offset 48, which is 8-aligned.
- Bits past the last slot, `m = 4*f*buckets`, in the final word, and any padding bytes, are zero.
- `f` and `buckets` are stored so a foreign reader needs no floating-point sizing. `fromBytes` recomputes `cuckooSizing(n, epsilon)` and rejects a frame whose stored values disagree. The body length is checked before anything is allocated, so a forged `n` can't request memory the body doesn't have.

**Files**
- Modify: `packages/distillate/src/cuckoo/cuckoo.ts`, `packages/distillate/tests/core/serialize.fuzz.test.ts`
- Test: `packages/distillate/tests/cuckoo/serialize.test.ts` (new)

### Task 1: A filter round-trips through bytes and JSON in the documented layout

**Files:** `src/cuckoo/cuckoo.ts`. Test: `tests/cuckoo/serialize.test.ts`

**Behavior:** `toBytes` writes the type 7 frame, and `fromBytes`/`fromJSON` restore a filter that re-serializes to identical bytes and gives the same answers.

**Test asserts:**
- `test.each` over four filters: empty `create(10, 0.01)`; `sampleStrings(40, 100)` into `create(100, 0.01, { seed: 5 })`; one filled to `n = 500` and then half deleted; one at `epsilon` 2e-9 (f = 32). For each:
  - `fromBytes(toBytes())` re-serializes byte-identically;
  - it has the same `count`/`buckets`/`fingerprintBits`/`seed`/`epsilon`;
  - it answers `has` identically over `sampleStrings(41, 2000)`.
- **Layout:** `readHeader` gives type 7 and variant 0. The body fields sit at the offsets above, and the body length is `32 + padded8(ceil(m/32)*4)`. The words start at frame offset 48, and `48 % 8 === 0`.
- **Reproducible:** two filters built separately from the same keys in the same order, with the same seed, give identical bytes.
- **JSON:** `fromJSON(toJSON())` re-serializes identically.

**Expected RED:** `f.toBytes is not a function` from `pnpm --filter distillate exec vitest run tests/cuckoo/serialize.test.ts`

**Implementation:**
- `toBytes` calls `writeFrame({ version: FORMAT_VERSION, type: 7, flags: HASH_MURMUR128 }, 32, padded8(words*4), fill)`. Words are written with `setUint32(..., true)`.
- `fromBytes` reads the header and params, constructs through the public constructor, then copies the words and sets `#count` (the class can reach its own private fields).
- `toJSON` and `fromJSON` wrap the frame in the shared envelope.

**Commit:** `feat(cuckoo): serialize as DSTL frame type 7`

### Task 2: `equals` matches byte equality

**Files:** `src/cuckoo/cuckoo.ts`. Test: `tests/cuckoo/serialize.test.ts`

**Behavior:** `a.equals(b)` is true exactly when `a.toBytes()` and `b.toBytes()` are equal.

**Test asserts:** fast-check over pairs built from random key arrays, with the pair kinds:
- the same build twice;
- one extra key;
- a different seed;
- one key deleted;
- a restored copy.

For each pair, `equals` equals `bytesEqual` of the two frames, and the generator is checked to produce both outcomes.

**Expected RED:** `a.equals is not a function` from the same command

**Implementation:** Compare `n`, `epsilon`, `seed`, `count`, and the words (via `bytesEqual` on the words' byte views). `f` and `buckets` follow from `n` and `epsilon`.

**Commit:** `feat(cuckoo): compare cuckoo filters by value`

### Task 3: Hostile frames never throw an untyped error or allocate past the body

**Files:** `src/cuckoo/cuckoo.ts`, `tests/core/serialize.fuzz.test.ts`. Test: the fuzz file plus a truncation test in `tests/cuckoo/serialize.test.ts`

**Behavior:** `fromBytes` checks the params length, the stored geometry and the exact body length before allocating, and turns a `ParamError` from bad params into a `SerializationError`.

**Test asserts:**
- `["cuckoo", ...]` joins the fuzz `entries`, over both arbitrary bytes and valid-framed bodies.
- Every truncated prefix of a filled filter's frame is rejected with a `SerializationError`.

**Expected RED:** an untyped `RangeError` (a `DataView` read past a short body) from `pnpm --filter distillate exec vitest run tests/core/serialize.fuzz.test.ts tests/cuckoo/serialize.test.ts`

**Implementation:**
- `assertMinBodyLength(body.length, 32, "cuckoo")`, then read `n`/`seed`/`epsilon`/`f`/`buckets`/`count`.
- `cuckooSizing(n, epsilon)`, with a `ParamError` rethrown as `SerializationError`. Reject a `SerializationError` if the stored `f` or `buckets` differ.
- `assertBodyLength` against `32 + padded8(ceil(4*f*buckets/32)*4)`, then construct.

**Commit:** `fix(cuckoo): check a frame's geometry and length before allocating`

### Task 4: Frames that parse but lie are rejected

**Files:** `src/cuckoo/cuckoo.ts`. Test: `tests/cuckoo/serialize.test.ts`

**Behavior:** Each inconsistent frame that Task 3 still accepts is refused with a named, typed error.

**Test asserts:** `test.each` of mutations applied to a filled filter's frame, each re-checksummed with `writeHeader`. Each must throw the listed class:

| Mutation | Error |
|---|---|
| type 1 | `SerializationError` |
| hash variant 1 | `UnknownHashVariantError` |
| nonzero params padding (byte 28) | `SerializationError` |
| nonzero bit past `m` in the final word | `SerializationError` |
| nonzero trailing pad byte | `SerializationError` |
| `count` off by one | `SerializationError` |
| `f` changed | `SerializationError` |
| `buckets` changed | `SerializationError` |
| `epsilon` 0 | `SerializationError` |

The padding cases use a filter whose word count is odd, and whose `m` isn't a multiple of 32.

**Expected RED:** `expected [Function] to throw an error` for the padding, tail-bit, count, type and variant cases, from `pnpm --filter distillate exec vitest run tests/cuckoo/serialize.test.ts`

**Implementation:**
- Check type and variant as `BloomFilter.fromBytes` does, and call `assertParamsPadding(body, 28, 32, "cuckoo")`.
- After copying the words: bits past `m` in the last word must be zero, and the pad bytes must be zero.
- Count the nonzero slots and require that to equal `count`.

**Commit:** `fix(cuckoo): reject frames whose padding or count disagree with the slots`

---

**Coverage:**
- Round-trip and JSON (1), `equals` (2), the typed rejections (3, 4), fuzz (3), and 8-byte alignment (1).
- Byte-identical frames for the same keys, a criterion moved here from #218, is task 1.

**Comment by akshay-xp** [comment]
**Tasks 1-4 complete** (`6659829`, `6896802`, `51f958b`, `aa7e347` on `worktree-cuckoo`, not pushed).

- The type 7 frame follows the pinned layout. A layout test reads it without `fromBytes` and finds each key's fingerprint where variant 0 puts it.
- Round-trips are byte-identical: empty, seeded, filled then half deleted, and 32-bit fingerprints. The JSON envelope round-trips, and the same keys in the same order give the same bytes.
- `equals` is structural and matches byte equality, checked by a property test that produces both outcomes.
- `fromBytes`:
  - checks type and variant, params length and padding;
  - recomputes the geometry from `n`/`epsilon` and matches the exact body length before allocating;
  - converts a `ParamError` to a `SerializationError`;
  - after loading, rejects bits set past the last slot, nonzero pad bytes, and a `count` that differs from the occupied slots.
- Cuckoo is in the serialization fuzz suite.

Deviations:
- Task 3: the truncated-prefix test passed at RED, because `readHeader`'s declared-length and CRC checks already reject a cut frame. The valid-framed fuzz supplied the RED: an untyped `DataView` `RangeError`.
- Task 4: the `f`, `buckets` and `epsilon` mutations passed at RED, because Task 3's geometry check already rejects them. They stay in the table as coverage. The other six cases were RED.

```
distillate: Test Files 38 passed, Tests 460 passed; eslint, tsc and prettier clean
```
